from typing import List

from objects import HashEntryObject

CUSTOM_HASHES: List[HashEntryObject] = [
    HashEntryObject(crc=int("d87f7e0c", 16), path_length=int(len("test")), file_path=str("test")),
    HashEntryObject(crc=int("d5c66d8b", 16), path_length=int(len("vshader_basic_pncu.vso")), file_path=str("vshader_basic_pncu.vso")),
    HashEntryObject(crc=int("af5a559a", 16), path_length=int(len("shaderspc")), file_path=str("shaderspc")),
    HashEntryObject(crc=int("e2a57f71", 16), path_length=int(len("TheRowBoat.zwo")), file_path=str("TheRowBoat.zwo")),
    HashEntryObject(crc=int("c26e55d8", 16), path_length=int(len("RowBoat")), file_path=str("RowBoat")),
HashEntryObject(crc=int("73c74981", 16), path_length=int(len("TheRowBoat")), file_path=str("TheRowBoat")),
HashEntryObject(crc=int("bc5377ee", 16), path_length=int(len("TheLeftOar")), file_path=str("TheLeftOar")),
HashEntryObject(crc=int("9fccd606", 16), path_length=int(len("TheRightOar")), file_path=str("TheRightOar")),
HashEntryObject(crc=int("04a34597", 16), path_length=int(len("BerkSplash")), file_path=str("BerkSplash")),
HashEntryObject(crc=int("849d9917", 16), path_length=int(len("dispenser")), file_path=str("dispenser")),
HashEntryObject(crc=int("c100b1f7", 16), path_length=int(len("jemmy2.zwo")), file_path=str("jemmy2.zwo")),
HashEntryObject(crc=int("b10218ca", 16), path_length=int(len("chain")), file_path=str("chain")),
HashEntryObject(crc=int("9946029f", 16), path_length=int(len("chestkey.zwo")), file_path=str("chestkey.zwo")),
HashEntryObject(crc=int("e11ee94d", 16), path_length=int(len("items")), file_path=str("items")),
HashEntryObject(crc=int("36736306", 16), path_length=int(len("circuit.zwo")), file_path=str("circuit.zwo")),
HashEntryObject(crc=int("f82fbd44", 16), path_length=int(len("digicode")), file_path=str("digicode")),
HashEntryObject(crc=int("a587b916", 16), path_length=int(len("textures")), file_path=str("textures")),
HashEntryObject(crc=int("8ae5542d", 16), path_length=int(len("door")), file_path=str("door")),
HashEntryObject(crc=int("341fecc8", 16), path_length=int(len("Crank2_cw.zwo")), file_path=str("Crank2_cw.zwo")),
HashEntryObject(crc=int("33bdfa58", 16), path_length=int(len("crank2")), file_path=str("crank2")),
HashEntryObject(crc=int("f96cb8e2", 16), path_length=int(len("Crank2_ccw.zwo")), file_path=str("Crank2_ccw.zwo")),
HashEntryObject(crc=int("e7d0ec13", 16), path_length=int(len("anims")), file_path=str("anims")),
HashEntryObject(crc=int("1253a6f5", 16), path_length=int(len("turbPause.zwo")), file_path=str("turbPause.zwo")),
HashEntryObject(crc=int("a9844195", 16), path_length=int(len("turb1.zwo")), file_path=str("turb1.zwo")),
HashEntryObject(crc=int("ee243b45", 16), path_length=int(len("turb2.zwo")), file_path=str("turb2.zwo")),
HashEntryObject(crc=int("b0d6b17c", 16), path_length=int(len("ken2")), file_path=str("ken2")),
HashEntryObject(crc=int("3307da19", 16), path_length=int(len("words.xmc")), file_path=str("words.xmc")),
HashEntryObject(crc=int("bb863ee1", 16), path_length=int(len("hacking")), file_path=str("hacking")),
HashEntryObject(crc=int("eb1ba939", 16), path_length=int(len("PDA.zwo")), file_path=str("PDA.zwo")),
HashEntryObject(crc=int("1fe61a83", 16), path_length=int(len("hcraise.zwo")), file_path=str("hcraise.zwo")),
HashEntryObject(crc=int("362c8d89", 16), path_length=int(len("hcase")), file_path=str("hcase")),
HashEntryObject(crc=int("f81d8ce0", 16), path_length=int(len("hcfall.zwo")), file_path=str("hcfall.zwo")),
HashEntryObject(crc=int("8d295663", 16), path_length=int(len("crowbar.zwo")), file_path=str("crowbar.zwo")),
HashEntryObject(crc=int("a9c7181d", 16), path_length=int(len("cardboard.zwo")), file_path=str("cardboard.zwo")),
HashEntryObject(crc=int("1ef438eb", 16), path_length=int(len("string.zwo")), file_path=str("string.zwo")),
HashEntryObject(crc=int("a9ccc0d4", 16), path_length=int(len("soda.zwo")), file_path=str("soda.zwo")),
HashEntryObject(crc=int("badfc00e", 16), path_length=int(len("bleach.zwo")), file_path=str("bleach.zwo")),
HashEntryObject(crc=int("248c0058", 16), path_length=int(len("acid.zwo")), file_path=str("acid.zwo")),
HashEntryObject(crc=int("c002b89f", 16), path_length=int(len("energydrink.zwo")), file_path=str("energydrink.zwo")),
HashEntryObject(crc=int("5c9e0a34", 16), path_length=int(len("glycerin.zwo")), file_path=str("glycerin.zwo")),
HashEntryObject(crc=int("f808f5f2", 16), path_length=int(len("ice.zwo")), file_path=str("ice.zwo")),
HashEntryObject(crc=int("3b8f2684", 16), path_length=int(len("Jemmy.zwo")), file_path=str("Jemmy.zwo")),
HashEntryObject(crc=int("fcc9a9e9", 16), path_length=int(len("jerrycan.zwo")), file_path=str("jerrycan.zwo")),
HashEntryObject(crc=int("343ea6e5", 16), path_length=int(len("lever.zwo")), file_path=str("lever.zwo")),
HashEntryObject(crc=int("07c2682e", 16), path_length=int(len("medikit.zwo")), file_path=str("medikit.zwo")),
HashEntryObject(crc=int("1e7f4dbd", 16), path_length=int(len("statuette.zwo")), file_path=str("statuette.zwo")),
HashEntryObject(crc=int("2cb82d9b", 16), path_length=int(len("syringe.zwo")), file_path=str("syringe.zwo")),
HashEntryObject(crc=int("29d8679b", 16), path_length=int(len("Welder.zwo")), file_path=str("Welder.zwo")),
HashEntryObject(crc=int("0743206f", 16), path_length=int(len("lockpick.zwo")), file_path=str("lockpick.zwo")),
HashEntryObject(crc=int("4793bdbe", 16), path_length=int(len("lockpick")), file_path=str("lockpick")),
HashEntryObject(crc=int("5a38922a", 16), path_length=int(len("heart.zwo")), file_path=str("heart.zwo")),
HashEntryObject(crc=int("22a6dfdf", 16), path_length=int(len("puzzle")), file_path=str("puzzle")),
HashEntryObject(crc=int("83147544", 16), path_length=int(len("talkie.zwo")), file_path=str("talkie.zwo")),
HashEntryObject(crc=int("34a86937", 16), path_length=int(len("chainsaw.zwo")), file_path=str("chainsaw.zwo")),
HashEntryObject(crc=int("520ebbe1", 16), path_length=int(len("weapons")), file_path=str("weapons")),
HashEntryObject(crc=int("0e06a223", 16), path_length=int(len("golfclub.zwo")), file_path=str("golfclub.zwo")),
HashEntryObject(crc=int("8750402d", 16), path_length=int(len("cross.zwo")), file_path=str("cross.zwo")),
HashEntryObject(crc=int("b663541c", 16), path_length=int(len("w_batclout.zwo")), file_path=str("w_batclout.zwo")),
HashEntryObject(crc=int("ea47be31", 16), path_length=int(len("bat.zwo")), file_path=str("bat.zwo")),
HashEntryObject(crc=int("43cbdfd4", 16), path_length=int(len("crossbow.zwo")), file_path=str("crossbow.zwo")),
HashEntryObject(crc=int("6181f18f", 16), path_length=int(len("dynamite.zwo")), file_path=str("dynamite.zwo")),
HashEntryObject(crc=int("090ba0fc", 16), path_length=int(len("flaregun.zwo")), file_path=str("flaregun.zwo")),
HashEntryObject(crc=int("e5beb5c4", 16), path_length=int(len("flashbang.zwo")), file_path=str("flashbang.zwo")),
HashEntryObject(crc=int("dfa625de", 16), path_length=int(len("flashball.zwo")), file_path=str("flashball.zwo")),
HashEntryObject(crc=int("500558ec", 16), path_length=int(len("flashlight.zwo")), file_path=str("flashlight.zwo")),
HashEntryObject(crc=int("0a685e38", 16), path_length=int(len("gun.zwo")), file_path=str("gun.zwo")),
HashEntryObject(crc=int("f2b391c3", 16), path_length=int(len("shotgun.zwo")), file_path=str("shotgun.zwo")),
HashEntryObject(crc=int("f55467d1", 16), path_length=int(len("taser.zwo")), file_path=str("taser.zwo")),
HashEntryObject(crc=int("812ce7ac", 16), path_length=int(len("uberflashlight.zwo")), file_path=str("uberflashlight.zwo")),
HashEntryObject(crc=int("b95fbd1a", 16), path_length=int(len("uzi.zwo")), file_path=str("uzi.zwo")),
HashEntryObject(crc=int("178cde7f", 16), path_length=int(len("Physics")), file_path=str("Physics")),
HashEntryObject(crc=int("f68f03c7", 16), path_length=int(len("Sounds")), file_path=str("Sounds")),
HashEntryObject(crc=int("e545a0c5", 16), path_length=int(len("settings")), file_path=str("settings")),
HashEntryObject(crc=int("4ef0ad97", 16), path_length=int(len("chests")), file_path=str("chests")),
HashEntryObject(crc=int("914a4c9f", 16), path_length=int(len("pause_pc.xmc")), file_path=str("pause_pc.xmc")),
HashEntryObject(crc=int("f872dc47", 16), path_length=int(len("save.xmc")), file_path=str("save.xmc")),
HashEntryObject(crc=int("7a49f9b9", 16), path_length=int(len("inventory_pc.xmc")), file_path=str("inventory_pc.xmc")),

]

#
#
#